# Generated by Django 2.0.7 on 2020-01-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
                ('create', models.TimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('detail', models.CharField(max_length=255, verbose_name='活动内容')),
                ('discount', models.CharField(max_length=255, verbose_name='折扣')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
                ('create', models.TimeField(auto_now_add=True)),
                ('open_id', models.CharField(max_length=255)),
                ('add', models.CharField(max_length=255, verbose_name='收货地址')),
                ('phone', models.CharField(max_length=255, verbose_name='收货电话')),
                ('rec_name', models.CharField(max_length=255, verbose_name='收货人姓名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BigOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
                ('create', models.TimeField(auto_now_add=True)),
                ('open_id', models.CharField(max_length=255, verbose_name='微信用户ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='订单号')),
                ('is_pay', models.BooleanField(default=0, verbose_name='是否支付')),
                ('is_send', models.BooleanField(default=0, verbose_name='是否接单')),
                ('is_sure', models.BooleanField(default=0, verbose_name='确认收货')),
                ('address', models.CharField(max_length=255, verbose_name='收货地址')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
                ('create', models.TimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='目录名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
                ('create', models.TimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='菜品名')),
                ('price', models.CharField(max_length=255, verbose_name='原单价')),
                ('img', models.ImageField(upload_to='static/img', verbose_name='展示图')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='api.Category', verbose_name='菜品分类')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
                ('create', models.TimeField(auto_now_add=True)),
                ('sale_num', models.CharField(max_length=255, verbose_name='销售量')),
                ('ingredient', models.CharField(max_length=255, verbose_name='配料')),
                ('dec', models.CharField(max_length=255, verbose_name='菜品描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmallOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
                ('create', models.TimeField(auto_now_add=True)),
                ('food_id', models.CharField(max_length=255, verbose_name='商品ID')),
                ('is_discount', models.BooleanField(default=0, verbose_name='折扣')),
                ('big_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='big_order', to='api.BigOrder', verbose_name='大订单')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
                ('create', models.TimeField(auto_now_add=True)),
                ('num', models.CharField(max_length=255, verbose_name='库存量')),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='food', to='api.Food', verbose_name='菜品')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='food',
            name='detail',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='food_detail', to='api.FoodDetail', verbose_name='菜品详情'),
        ),
        migrations.AddField(
            model_name='active',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='food_active', to='api.Food', verbose_name='菜品'),
        ),
    ]
