# Generated by Django 2.0.7 on 2020-01-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigorder',
            name='is_pay',
        ),
        migrations.RemoveField(
            model_name='bigorder',
            name='is_send',
        ),
        migrations.RemoveField(
            model_name='bigorder',
            name='is_sure',
        ),
        migrations.AddField(
            model_name='bigorder',
            name='status',
            field=models.CharField(choices=[(0, '未支付'), (1, '已支付'), (2, '以接单'), (3, '订单完成')], default=0, max_length=255, verbose_name='订单状态'),
        ),
    ]
