# Generated by Django 2.0.7 on 2020-01-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200105_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigorder',
            name='status',
        ),
        migrations.AddField(
            model_name='bigorder',
            name='all_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smallorder',
            name='food_name',
            field=models.CharField(default=None, max_length=255, verbose_name='商品名字'),
        ),
        migrations.AddField(
            model_name='smallorder',
            name='food_num',
            field=models.CharField(default=None, max_length=255, verbose_name='购买数量'),
        ),
        migrations.AddField(
            model_name='smallorder',
            name='food_price',
            field=models.CharField(default=None, max_length=255, verbose_name='商品价格'),
        ),
    ]
